### ISSUE TITLE
OSPF support

### ISSUE THREAD

**Issue by petercrocker** [cpmarvin/lnetd#7]
Hey @cpmarvin I've now got a use case for this at the edge of our multiple DCs, but would need OSPF support! Are you thinking about this at all yet?

**Comment by cpmarvin** [comment]
hi @petercrocker ,

there is an BGP-LS support now that should cover all other vendors (https://github.com/cpmarvin/lnetd/wiki/BGP-LS-Topology) and ospf support via juniper(https://github.com/cpmarvin/lnetd/tree/master/inputs/jnp_ospf_ted_links)

What vendor are you looking for ? i might be able to develop some input plugin for it if bgp-ls is not enough.

**Comment by cpmarvin** [comment]
Closing this now. Please reopen if needed
